site_name: Документация к лабораторным работам
nav:
  - Home: index.md
  - Лабораторная работа номер 1:
      - "Task 1": Lr1/task_1.md
      - "Task 2": Lr1/task_2.md
      - "Task 3": Lr1/task_3.md
      - "Task 4": Lr1/task_4.md
      - "Task 5": Lr1/task_5.md
  - Лабораторная работа номер 2:
    - Выполнение: Lr2/implementation.md
  - Лабораторная работа номер 3:
      - Практическое задание: Lr3/practice.md
      - Выполнение: Lr3/implementation.md
  - Лабораторная работа номер 4:
      - Выполнение: Lr4/implementation.md
theme:
  name: material