# Generated by Django 5.1.2 on 2024-11-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0002_tour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='available_seats',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
