# Generated by Django 5.1.2 on 2024-11-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0003_tour_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
