# Generated by Django 5.1.2 on 2024-12-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_quartergrade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.IntegerField(),
        ),
    ]
